version: "3.7"
services:
  app-name:
    build:
      context: .
    image: nlpproj:1.0.0
    container_name: nlpproj
    ports:
      - "80:5050"
    environment:
      - TARGET=$TARGET
    restart: unless-stopped